fix: use python 3.13 in CI to work around job error
ansible-lint .
Traceback (most recent call last):
  File "/usr/local/bin/ansible-lint", line 3, in <module>
    from ansiblelint.__main__ import _run_cli_entrypoint
  File "/usr/local/lib/python3.14/site-packages/ansiblelint/__main__.py", line 36, in <module>
    from ansible_compat.prerun import get_cache_dir
  File "/usr/local/lib/python3.14/site-packages/ansible_compat/prerun.py", line 22, in <module>
    raise RuntimeError(msg)
RuntimeError: Python 3.14 requires ansible-core version >= 2.20.0, and we found 2.19.3.